"""V2

Revision ID: 01103fe0d37a
Revises: bcc26ea59aae
Create Date: 2023-06-18 01:23:58.364142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01103fe0d37a'
down_revision = 'bcc26ea59aae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'permissions',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'permissions',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=False)
    # ### end Alembic commands ###
